"""Programming languages and technologies that David Oelfke has experience with."""

TECHNOLOGIES = [
    ".NET",
    "AI",
    "Ant Design (AntD)",
    "Artificial Intelligence",
    "AWS",
    "Akamai",
    "Amplitude",
    "Angular",
    "Apollo",
    "Auth0",
    "Azure",
    "Azure AD",
    "Backblaze",
    "Bash",
    "Bitbucket",
    "Bootstrap",
    "Brightcove",
    "C#",
    "CSS",
    "Class Validator",
    "CloudFront",
    "Cloudflare",
    "CloudWatch",
    "Cognito",
    "Contentful",
    "Cordova",
    "Datadog",
    "Dataloader",
    "Day.js",
    "Docker",
    "Elastic Bean Stalk (ELB)",
    "Elasticsearch",
    "ESLint",
    "Emotion",
    "Entity Framework",
    "Express.js",
    "Firebase",
    "Fly.io",
    "GCP",
    "Git",
    "GitHub",
    "GitLab",
    "Google Analytics",
    "Grafana",
    "GraphQL",
    "HTML",
    "Heroku",
    "Jade",
    "Java",
    "JavaScript",
    "Jeckyll",
    "Jest",
    "Jira",
    "jQuery",
    "Knockout",
    "Kubernetes",
    "LangChain",
    "LDAP",
    "LESS",
    "Lambdas",
    "Launch Darkly",
    "Lerna",
    "Linq",
    "Lodash",
    "Logz.io",
    "Lucene",
    "Mailgun",
    "Mantine",
    "Material UI (MUI)",
    "MixPanel",
    "ML",
    "Machine Learning"
    "Mocha",
    "Moment",
    "MongoDB",
    "Mongoose",
    "Monorepo",
    "MSBuild",
    "MSGraph",
    "MySQL",
    "Nest.js",
    "Netlify",
    "New Relic",
    "Next.js",
    "Node.js",
    "NPM",
    "Nuxt",
    "Open AI",
    "Oracle DB",
    "PHP",
    "Pinecone",
    "PNPM",
    "Postgres",
    "Powershell",
    "Prisma",
    "Pug",
    "Python",
    "RAG",
    "Retrieval-Augmented Generation"
    "REST",
    "React",
    "React Hook Form",
    "React Query",
    "Redis",
    "Remix",
    "RxJS",
    "S3",
    "SCSS",
    "Segment",
    "SendGrid",
    "SES",
    "Slack",
    "SQS",
    "Styled Components",
    "Supabase",
    "Swagger",
    "Tailwind",
    "tRPC",
    "Turborepo",
    "TypeORM",
    "TypeScript",
    "Underscore",
    "Vector Databases",
    "Vercel",
    "Visual Basic",
    "Vite",
    "Vitest",
    "Vue",
    "WebAPI",
    "Webpack",
    "WordPress",
    "Yarn",
    "Yup",
    "Zod",
]
