"""Work history data for David Oelfke."""

qloo = {
    "companyName": "Qloo",
    "position": "Lead Software Engineer",
    "startDate": "Jan 2025",
    "endDate": "Present",
    "accomplishments": [
        "Led development of version 2 — the world's first Taste AI platform.",
        "Built an onshore engineering team and modernized best practices.",
        "Developed secure dashboard sharing, multi-user editing, and in-app help systems.",
        "Migrated codebase from JavaScript to TypeScript.",
        "Resolved major architectural bottlenecks and introduced metrics tooling for continuous engineering improvement.",
    ],
    "domains": ["Qloo.com"],
    "programming languages and technologies": [
        "AI",
        "Artificial Intelligence",
        "CSS",
        "Day.js",
        "ESLint",
        "Express.js",
        "FastAPI",
        "Git",
        "GitHub",
        "HTML",
        "JavaScript",
        "Jest",
        "LangChain",
        "Lambdas",
        "Machine Learning",
        "Material UI (MUI)",
        "ML",
        "Monorepo",
        "Next.js",
        "Node.js",
        "Open AI",
        "PNPM",
        "Python",
        "React",
        "React Query",
        "REST",
        "Styled Components",
        "TypeScript",
        "Vercel",
        "Webpack",
    ],
}

sayari = {
    "companyName": "Sayari",
    "position": "Principal Software Engineer",
    "startDate": "Feb 2024",
    "endDate": "Jan 2025",
    "accomplishments": [
        "Rearchitected frontend apps for better scalability and maintainability.",
        "Developed the company's first AI product to summarize large datasets, speeding analyst workflows.",
        "Built an AI-driven data pipeline to boost consolidation accuracy.",
        "Led development of the company's second major product (Map) and migrated codebase to a shared monorepo.",
        "Implemented a feature flag system and modernized engineering practices (TypeScript, SCSS modules, Slack build alerts, CI).",
        "Introduced a pod-based team structure for faster, autonomous delivery.",
        "Created internal tools (auto-recovering Kubernetes forwarding, Storybook, custom Chrome extension) and led frontend practice initiatives.",
    ],
    "domains": ["Sayari.com"],
    "programming languages and technologies": [
        "AI",
        "Artificial Intelligence",
        "CSS",
        "CloudWatch",
        "Day.js",
        "Elasticsearch",
        "ESLint",
        "Emotion",
        "Express.js",
        "GCP",
        "Git",
        "GitHub",
        "HTML",
        "JavaScript",
        "Jest",
        "Kubernetes",
        "Machine Learning",
        "Material UI (MUI)",
        "ML"
        "MixPanel",
        "Monorepo",
        "Node.js",
        "Open AI",
        "Pinecone",
        "PNPM",
        "Postgres",
        "Python",
        "RAG"
        "REST",
        "React Hook Form",
        "React Query",
        "Redis",
        "Redux",
        "RxJS",
        "SCSS",
        "Styled Components",
        "TypeScript",
        "Vector Databases",
        "Vite",
        "Zod",
    ],
}

freelance = {
    "companyName": "Freelance",
    "position": "Principal Software Engineer",
    "startDate": "Apr 2023",
    "endDate": "Feb 2024",
    "accomplishments": [
        "Built out products for multiple startups and went through YC.",
        "Onbrand - product lifecycle management for the fashion industry.",
        "Sibble & Associates - viability reports for startups to help them raise funds.",
        "Trayd - same day payroll for construction workers.",
        "Upwell - invoicing automation for trucking / logistics.",
    ],
    "domains": [
        "OnbrandPLM.com",
        "BuildTrayd.com",
        "SibbleAssociates.com",
        "Upwell.com",
    ],
    "programming languages and technologies": [
        "AI",
        "Auth0",
        "CSS",
        "Cloudflare",
        "Docker",
        "ESLint",
        "Emotion",
        "Express.js",
        "Firebase",
        "Fly.io",
        "GCP",
        "Git",
        "GitHub",
        "HTML",
        "JavaScript",
        "Jest",
        "Lambdas",
        "Mantine",
        "Material UI (MUI)",
        "Monorepo",
        "Netlify",
        "Next.js",
        "Node.js",
        "NPM",
        "Open AI",
        "PNPM",
        "Postgres",
        "Prisma",
        "REST",
        "React",
        "React Hook Form",
        "React Query",
        "Remix",
        "S3",
        "SCSS",
        "SendGrid",
        "Supabase",
        "Tailwind",
        "tRPC",
        "Turborepo",
        "TypeScript",
        "Vercel",
        "Zod",
    ],
}

microsoft = {
    "companyName": "Microsoft",
    "position": "Principal Software Engineer / Lead",
    "startDate": "May 2021",
    "endDate": "Apr 2023",
    "accomplishments": [
        "Led security, web, and devops related projects.",
        "Increased communication and teamwork within the immediate team.",
        "Reduced PR turn over time within the Azure organization.",
        "Restructured all teams to be full-stack within the organization.",
        "Evaluated new hardware for developers in the organization.",
    ],
    "domains": ["Portal.Azure.com"],
    "programming languages and technologies": [
        ".NET",
        "Azure",
        "Azure AD",
        "C#",
        "CSS",
        "ESLint",
        "Git",
        "GraphQL",
        "HTML",
        "JavaScript",
        "Jest",
        "Knockout",
        "LDAP",
        "Linq",
        "Monorepo",
        "MSBuild",
        "MSGraph",
        "NPM",
        "React",
        "Styled Components",
        "TypeScript",
    ],
}


rocket = {
    "companyName": "Rocket Insights",
    "position": "Principal Software Engineer",
    "startDate": "Nov 2017",
    "endDate": "May 2021",
    "accomplishments": [
        "Led, built, and  launched over 15 product across many industries.",
        "Hired the second generation of engineers.",
        "Expanded the company to the west coast.",
        "Created a framework that's used at multiple clients and helped many of them build or scale their engineering practices.",
    ],
    "domains": ["RocketInsights.com", "DeptAgency.com"],
    "programming languages and technologies": [
        "Ant Design (AntD)",
        "AWS",
        "Amplitude",
        "Apollo",
        "Auth0",
        "Brightcove",
        "CSS",
        "Class Validator",
        "CloudFront",
        "Cognito",
        "Contentful",
        "Cordova",
        "Dataloader",
        "Docker",
        "ESLint",
        "Emotion",
        "Express.js",
        "Git",
        "Github",
        "Google Analytics",
        "GraphQL",
        "HTML",
        "Heroku",
        "JavaScript",
        "Jest",
        "Lambdas",
        "Launch Darkly",
        "Lerna",
        "Material UI (MUI)",
        "Moment",
        "Monorepo",
        "Nest.js",
        "Netlify",
        "Next.js",
        "Node.js",
        "NPM",
        "Nuxt",
        "Postgres",
        "REST",
        "React",
        "Redis",
        "S3",
        "SCSS",
        "SendGrid",
        "SES",
        "Slack",
        "Styled Components",
        "TypeORM",
        "TypeScript",
        "Vercel",
        "Vue",
        "Webpack",
        "Yarn",
        "Yup",
    ],
}

buildium = {
    "companyName": "Buildium",
    "position": "Senior Software Engineering Manager",
    "startDate": "Dec 2013",
    "endDate": "Nov 2017",
    "accomplishments": [
        "Lead engineer for the accounting platform.",
        "Managed and led multiple teams.",
        "Increased predictability across teams.",
        "Completely revamped front-end practices.",
        "Migrated to AWS.",
        "Built out the devops team and practices.",
        "Led the organization for most security bounties.",
    ],
    "domains": ["Buildium.com"],
    "programming languages and technologies": [
        ".NET",
        "AWS",
        "Akamai",
        "Angular",
        "Bitbucket",
        "C#",
        "CSS",
        "Elasticsearch",
        "Git",
        "HTML",
        "JavaScript",
        "jQuery",
        "Knockout",
        "LESS",
        "Lambdas",
        "Linq",
        "Lodash",
        "Lucene",
        "Mailgun",
        "Moment",
        "MySQL",
        "New Relic",
        "Powershell",
        "REST",
        "S3",
        "SendGrid",
        "SES",
        "SQS",
        "Underscore",
        "WebAPI",
    ],
}

rls = {
    "companyName": "RLS2000.com",
    "position": "CTO",
    "startDate": "Nov 2010",
    "endDate": "Dec 2013",
    "accomplishments": [
        "Led several greenfield projects, with ownership over engineering and IT.",
        "Migrated servers to a scalable architecture with full redundancy and high availability.",
        "Modernized IT and development practices.",
    ],
    "domains": ["TryElevate.com"],
    "programming languages and technologies": [
        ".NET",
        "Azure",
        "C#",
        "CSS",
        "HTML",
        "JavaScript",
        "jQuery",
        "Linq",
        "Lodash",
        "Node.js",
        "NPM",
        "Underscore",
        "WordPress",
    ],
}

tsd = {
    "companyName": "TSD",
    "position": "Lead / Senior Software Engineer",
    "startDate": "Nov 2012",
    "endDate": "Jun 2013",
    "accomplishments": [
        "Led development on TSD Loaner.",
        "Architected new projects (WebDRIVE and first mobile apps).",
        "Introduced responsive web design.",
        "Revamped / designed the new UI for Loaner.",
        "Identified and fixed major security issues.",
        "Improved engineering practices and company culture.",
        "Oversaw public website development.",
    ],
    "domains": ["TSDWeb.com"],
    "programming languages and technologies": [
        ".NET",
        "CSS",
        "HTML",
        "JavaScript",
        "jQuery",
        "Linq",
        "MySQL",
        "WebAPI",
    ],
}

emc = {
    "companyName": "EMC",
    "position": "Software Engineer",
    "startDate": "Jan 2007",
    "endDate": "Nov 2010",
    "accomplishments": [
        "Ownership, development, and administration of various 1st and 3rd party webs apps and tools."
    ],
    "domains": ["Dell.com"],
    "programming languages and technologies": [
        ".NET",
        "CSS",
        "Entity Framework",
        "HTML",
        "JavaScript",
        "LDAP",
        "Linq",
        "MySQL",
        "Oracle DB",
        "PHP",
    ],
}

cdu = {
    "companyName": "Computers Down Under",
    "position": "Bench Manager",
    "startDate": "Oct 2003",
    "endDate": "Dec 2007",
    "accomplishments": [
        "Managed the 'front' of the store (everything except finances).",
        "Oversaw other technicians.",
        "Created / optimizing processes to increase profitability, productivity, and quality.",
    ],
    "domains": [],
}

WORK_HISTORY = [
    qloo,
    sayari,
    freelance,
    microsoft,
    rocket,
    buildium,
    rls,
    tsd,
    emc,
    cdu,
]
